version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --bind_ip 0.0.0.0

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - EXTERNAL_MONGO_URI=mongodb://localhost:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
